### ISSUE TITLE
mail - bug

### ISSUE THREAD

**Issue by leebaird** [sensepost/thumbscr-ews#6]
Kali Linux 2020.4 rolling, completely patched.

└─# python3 --version
Python 3.9.1+

└─# python3 thumbscr-ews.py -C test.yml --exch-host webmail.acme.com mail read
Traceback (most recent call last):
  File "/root/EWS/thumbscr-ews/thumbscr-ews.py", line 6, in <module>
    cli()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/EWS/thumbscr-ews/thumbscrews/cli.py", line 186, in read
    account = Account(username, config=config, autodiscover=False, access_type=DELEGATE)
  File "/usr/local/lib/python3.9/dist-packages/exchangelib/account.py", line 132, in __init__
    self.version = self.protocol.version
  File "/usr/local/lib/python3.9/dist-packages/exchangelib/protocol.py", line 437, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "/usr/local/lib/python3.9/dist-packages/exchangelib/version.py", line 230, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "/usr/local/lib/python3.9/dist-packages/exchangelib/services/resolve_names.py", line 32, in call
    for elem in elements:
  File "/usr/local/lib/python3.9/dist-packages/exchangelib/services/common.py", line 118, in _get_elements
    for i in self._response_generator(payload=payload):
  File "/usr/local/lib/python3.9/dist-packages/exchangelib/services/common.py", line 109, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python3.9/dist-packages/exchangelib/services/common.py", line 173, in _get_response_xml
    r, session = post_ratelimited(
  File "/usr/local/lib/python3.9/dist-packages/exchangelib/util.py", line 814, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "/usr/local/lib/python3.9/dist-packages/exchangelib/util.py", line 891, in _raise_response_errors
    raise UnauthorizedError('Invalid credentials for %s' % response.url)
exchangelib.errors.UnauthorizedError: Invalid credentials for https://webmail.acme.com/EWS/Exchange.asmx

**Comment by cablethief** [comment]
looks as though your credentials are invalid.
